---
name: "Build: Personal Repos"

on:
  push:
    branches:
      - main
    paths:
      - build_personal.py
      - pyproject.toml
      - .github/workflows/build_personal_repos.yml
  workflow_dispatch:
  schedule:
    - cron: '32 * * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repo"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          token: ${{secrets.SOURCE_PUSH_TOKEN}}

      - name: "Set up Python"
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3.x

      - name: "Install Python dependencies"
        run: |
          python -m pip install -e ".[dev]"

      - name: "Update Repos"
        env:
          SOURCE_PUSH_TOKEN: ${{ secrets.SOURCE_PUSH_TOKEN }}
        run: |-
          python build_personal.py
          cat README.md

      - name: "Commit and push if repos changed"
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          commit_message: "Updated personal repos"
          file_pattern: "personal/repos.lst"
          commit_user_name: "fun-sqlfmt[bot]"
          commit_user_email: "credfeto@users.noreply.github.com"
          commit_author: "repos-bot[bot] <credfeto@users.noreply.github.com>"
          skip_dirty_check: false
