name: Build Personal Repos

on:
  push:
    branches:
      - main
    paths:
      - build_personal.py
      - requirements.txt
      - .github/workflows/build_personal_repos.yml
  workflow_dispatch:
  schedule:
    - cron:  '32 * * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "Check out repo"
      uses: actions/checkout@v4.1.0
      token: ${{secrets.SOURCE_PUSH_TOKEN}}

    - name: "Set up Python"
      uses: actions/setup-python@v5.0.0
      with:
        python-version: 3.x

    - name: "Install Python dependencies"
      run: |
        python -m pip install -r requirements.txt

    - name: "Update Repos"
      env:
        SOURCE_PUSH_TOKEN: ${{ secrets.SOURCE_PUSH_TOKEN }}
      run: |-
        python build_personal.py
        cat README.md

    - name: "Commit and push if repos changed"
      uses: stefanzweifel/git-auto-commit-action@v5.1.0
      with:
        commit_message: "Updated personal repos"
        file_pattern: "personal/repos.lst"
        commit_user_name: "fun-sqlfmt[bot]"
        commit_user_email: "credfeto@users.noreply.github.com"
        commit_author: "repos-bot[bot] <credfeto@users.noreply.github.com>"
        skip_dirty_check: false
