name: Build Personal Repos

on:
  push:
    branches:
      - main
    paths:
      - build_personal.py
      - requirements.txt
      - .github/workflows/build_personal_repos.yml
  workflow_dispatch:
  schedule:
    - cron:  '32 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v3.1.0
    - name: Set up Python
      uses: actions/setup-python@v4.4.0
      with:
        python-version: 3.x
    - uses: actions/cache@v3.0.11
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Update Repos
      env:
        SOURCE_PUSH_TOKEN: ${{ secrets.SOURCE_PUSH_TOKEN }}
      run: |-
        python build_personal.py
        cat README.md
    - name: Commit and push if README changed
      run: |-
        git diff
        git config --global user.email "credfeto@users.noreply.github.com"
        git config --global user.name "Repos-bot"
        git diff --quiet || (git add personal/repos.lst && git commit -m "Updated personal repos")
        git push
