name: "Build and deploy to github pages"

on:
  push:
    branches:
      - main  # Set a branch to deploy
    paths:
      - packages.json
      - release.config
      - personal/repos.lst
      - funfair/repos.lst
      - .github/workflows/deploy-to-github-pages.yml
jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: "Checkout Source"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Remove gitignore"
        run: rm -f ./public/.gitignore

      - name: "Build"
        run: |
          mkdir ./public
          cp packages.json ./public/packages.config
          cp release.config ./public/release.config
          cp personal/repos.lst ./personal-repos.config
          cp funfair/repos.lst ./funfair-repos.config

      - name: "Deploy"
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: updates.markridgwell.com
