name: "Build and deploy to github pages"

on:
  push:
    branches:
      - main  # Set a branch to deploy
    paths:
      - packages.json
      - release.config
      - personal/repos.lst
      - funfair/repos.lst
      - .github/workflows/deploy-to-github-pages.yml
jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    env:
      TARGET: ./public

    steps:
      - name: "Checkout Source"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Remove gitignore"
        run: rm -f "${{env.TARGET}}/.gitignore"

      - name: "Build"
        run: |
          mkdir "${{env.TARGET}}/"
          cp packages.json "${{env.TARGET}}/packages.config"
          cp release.config "${{env.TARGET}}/release.config"
          cp personal/repos.lst "${{env.TARGET}}/personal-repos.config"
          cp funfair/repos.lst "${{env.TARGET}}/funfair-repos.config"

      - name: "Deploy"
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "${{env.TARGET}}"
          cname: updates.markridgwell.com
