name: Update Repo Settings

on:
  push:
    branches:
      - main
    paths:
      - personal/repos.lst
      - update_repos.py
      - requirements.txt
      - .github/workflows/update_repo_settings.yml
  schedule:
    - cron:  '55 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v4.1.0
    - name: Set up Python
      uses: actions/setup-python@v5.0.0
      with:
        python-version: 3.x
    - uses: actions/cache@v4.0.0
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Update Repos
      env:
        SOURCE_PUSH_TOKEN: ${{ secrets.SOURCE_PUSH_TOKEN }}
      run: |-
        python update_repos.py
